from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from fastapi.responses import FileResponse
from datetime import datetime
import uuid
import math
import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from pathlib import Path
from typing import Optional

load_dotenv()

base_dir = Path(__file__).parent.parent.resolve()
if str(base_dir) not in sys.path:
    sys.path.insert(0, str(base_dir))

try:
    from supabase_client import load_db, save_db, UPLOADS_DIR
except ImportError:
    from backend.supabase_client import load_db, save_db, UPLOADS_DIR

router = APIRouter(prefix="/road-scar", tags=["Road Scar Pipeline"])

def haversine_m(lat1, lon1, lat2, lon2):
    """Returns distance in meters"""
    R = 6371000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
    return 2 * R * math.asin(math.sqrt(a))

def gemini_verify_mock(description: str, damage_type: str) -> bool:
    """
    Mocking Gemini Vision Verification.
    In production: pass image_bytes to genai.GenerativeModel('gemini-1.5-pro-vision')
    For the demo, we assume verification passes if it's a valid damage type.
    """
    valid_types = ['pothole', 'broken_divider', 'waterlogging', 'missing_signage']
    return damage_type.lower() in valid_types or 'dangerous' in description.lower()

async def file_complaint(reports, damage_type, lat, lng):
    ref_id = f"SURAKSHA-AI-{str(uuid.uuid4())[:8].upper()}"

    # --- PDF banao ---
    pdf_path = f"uploads/complaint_{ref_id}.pdf"
    
    # Ensure directory exists
    os.makedirs("uploads", exist_ok=True)
    
    c = canvas.Canvas(pdf_path, pagesize=A4)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 780, "ROAD DAMAGE COMPLAINT")
    c.drawString(50, 760, "SURAKSHA-AI Intelligent Road Safety System")

    c.setFont("Helvetica", 12)
    c.drawString(50, 720, f"Reference ID  : {ref_id}")
    c.drawString(50, 700, f"Damage Type   : {damage_type}")
    c.drawString(50, 680, f"GPS Location  : {lat:.6f}, {lng:.6f}")
    c.drawString(50, 660, f"Google Maps   : maps.google.com/?q={lat},{lng}")
    c.drawString(50, 640, f"Total Reports : {len(reports)} verified citizens")
    c.drawString(50, 620, f"Filed On      : {datetime.now().strftime('%d %B %Y, %I:%M %p')}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, 580, "Individual Reports:")

    c.setFont("Helvetica", 10)
    y = 560
    for r in reports:
        dt_str = r.get('created_at', datetime.now().isoformat())[:19].replace("T", " ")
        c.drawString(60, y, f"- {dt_str}  |  ({r['lat']:.4f}, {r['lon']:.4f})")
        y -= 18

    c.setFont("Helvetica", 10)
    c.drawString(50, y - 20, "This complaint has been automatically generated by the SURAKSHA-AI system.")
    c.drawString(50, y - 36, "IIT Madras Road Safety Hackathon 2026.")

    c.save()

    # --- Email bhejo ---
    try:
        sender   = os.getenv("SENDER_EMAIL")
        password = os.getenv("SENDER_PASSWORD")
        receiver = os.getenv("RECEIVER_EMAIL")

        if sender and password and receiver:
            msg = MIMEMultipart()
            msg["From"]    = sender
            msg["To"]      = receiver
            msg["Subject"] = f"[SURAKSHA-AI ALERT] Road Damage Complaint {ref_id}"

            body = f"""Respected Sir/Madam,

This complaint has been automatically filed by the SURAKSHA-AI Road Safety System.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COMPLAINT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Reference ID  : {ref_id}
Damage Type   : {damage_type}
GPS Location  : {lat:.6f}, {lng:.6f}
Google Maps   : https://maps.google.com/?q={lat},{lng}
Verified By   : {len(reports)} citizen reports + Gemini AI
Filed On      : {datetime.now().strftime('%d %B %Y, %I:%M %p')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{len(reports)} different citizens have reported road damage in this zone.
The complaint was auto-filed after Gemini AI verification.

Please take immediate action.

The PDF complaint is attached with this email.

Regards,
SURAKSHA-AI Automated Road Safety System
IIT Madras Road Safety Hackathon 2026
"""

            msg.attach(MIMEText(body, "plain"))

            # PDF attach karo
            with open(pdf_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename=Complaint_{ref_id}.pdf"
                )
                msg.attach(part)

            # Send karo
            with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                server.login(sender, password)
                server.sendmail(sender, receiver, msg.as_string())

            print(f"[EMAIL SENT] {ref_id} → {receiver}")
        else:
            print("[EMAIL SKIPPED] Missing env credentials.")

    except Exception as e:
        print(f"[EMAIL FAILED] {e}")

    return ref_id

@router.post("/report")
async def report_road_damage(
    lat: float = Form(...),
    lon: float = Form(...),
    damage_type: str = Form(...),
    description: str = Form(""),
    photo: Optional[UploadFile] = File(None)
):
    """
    Step 1 & 2: Receive report and verify via Gemini Vision.
    """
    try:
        db = load_db()
        if "road_scars" not in db: db["road_scars"] = []
        if "road_scar_clusters" not in db: db["road_scar_clusters"] = []
        if "road_scar_drafts" not in db: db["road_scar_drafts"] = []

        report_id = str(uuid.uuid4())
        
        # Mock Gemini Verification
        is_verified = gemini_verify_mock(description, damage_type)
        
        report = {
            "id": report_id,
            "lat": lat,
            "lon": lon,
            "damage_type": damage_type,
            "description": description,
            "is_verified": is_verified,
            "clustered": False,
            "created_at": datetime.now().isoformat()
        }
        db["road_scars"].append(report)
        
        # Step 3: Threshold check (Cluster reports within 100m)
        if is_verified:
            nearby_verified = [
                r for r in db["road_scars"] 
                if r["is_verified"] and not r.get("clustered", False) and 
                haversine_m(lat, lon, r["lat"], r["lon"]) <= 100
            ]
            
            # If 3 or more verified reports in the same zone
            if len(nearby_verified) >= 3:
                cluster_id = str(uuid.uuid4())
                
                for r in nearby_verified:
                    r["clustered"] = True
                    r["cluster_id"] = cluster_id
                
                cluster = {
                    "id": cluster_id,
                    "lat": lat,
                    "lon": lon,
                    "reports": [r["id"] for r in nearby_verified],
                    "created_at": datetime.now().isoformat()
                }
                db["road_scar_clusters"].append(cluster)
                
                # Step 4 & 5: Auto Complaint Drafting & Dispatch
                ref_id = await file_complaint(nearby_verified, damage_type, lat, lon)
                
                draft = {
                    "id": ref_id,
                    "cluster_id": cluster_id,
                    "agency": "NHAI / PWD",
                    "lat": lat,
                    "lon": lon,
                    "damage_type": damage_type,
                    "status": "Sent via Email",
                    "created_at": datetime.now().isoformat(),
                    "pdf_path": f"uploads/complaint_{ref_id}.pdf"
                }
                
                db["road_scar_drafts"].append(draft)
                
                save_db(db)
                return {
                    "status": "success", 
                    "message": "Damage verified. Threshold reached. Complaint auto-drafted and sent to NHAI.",
                    "draft_id": draft["id"]
                }
                
        save_db(db)
        return {"status": "success", "message": "Damage logged and verified.", "verified": is_verified}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/status")
async def get_pipeline_status():
    """
    Returns pipeline status for the admin dashboard.
    """
    db = load_db()
    return {
        "reports": db.get("road_scars", []),
        "clusters": db.get("road_scar_clusters", []),
        "drafts": db.get("road_scar_drafts", [])
    }

@router.get("/complaint-pdf/{cluster_id}")
async def get_complaint_pdf(cluster_id: str):
    """
    Returns the actual PDF document generated by reportlab.
    """
    db = load_db()
    drafts = db.get("road_scar_drafts", [])
    draft = next((d for d in drafts if d.get("cluster_id") == cluster_id), None)
    
    if draft and "pdf_path" in draft and os.path.exists(draft["pdf_path"]):
        return FileResponse(draft["pdf_path"], media_type="application/pdf", filename=f"Complaint_{draft['id']}.pdf")
        
    raise HTTPException(status_code=404, detail="PDF not found")

